
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: install_essentials
      run: sudo apt install -y build-essential
    - name: install_testsuite
      run: sudo apt install -y libcppunit-dev
    - name: configure_x
      run: sudo chmod +x ./configure 
    - name: some_checks_upfront
      run: ls -l & whoami
    - name: configure
      run: sudo ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck



